// <auto-generated />
namespace WebApplication3_codefirst_Empdepdsg_layout_101.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Initload : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initload));
        
        string IMigrationMetadata.Id
        {
            get { return "202602131801373_Initload"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
